### ISSUE TITLE
Fails to compile

### ISSUE THREAD

**Issue by kirkov** [jccovey/watch-lessc#3]
$ watch-lessc -i main.less -o main.css

	watch-lessc: Updated: C:\xxxxx\css\main.css

	c:\Users\xxx\AppData\Roaming\npm\node_modules\watch-lessc\node_modules\less\lib\less\parser\parser.js:108
				imports.contents[fileInfo.filename] = str;
					   ^
	TypeError: Cannot read property 'contents' of undefined
		at Object.Parser.parse (c:\Users\xxx\AppData\Roaming\npm\node_modules\watch-lessc\node_modules\less\lib\less\parser\parser.js:108:20)
		at c:\Users\xxx\AppData\Roaming\npm\node_modules\watch-lessc\app.js:43:16
		at fs.js:271:14
		at Object.oncomplete (fs.js:107:15)

**Comment by drhayes** [comment]
I'm getting this too. Any workarounds?

**Comment by jccovey** [comment]
I was specifying the latest version of less at the time I created this package, but version 2.0 of less introduced significant changes to the API. I updated the package manifest to force npm to install the latest 1.x version of less when watch-lessc is installed.

Please uninstall watch-lessc and less and then install watch-lessc again to get the newest, compatible version of less (currently 1.75).
